# Generated by Django 6.0.3 on 2026-03-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('mesaj', models.TextField(default='Spune-ne ce crezi, fără frică. Sau cu frică, dar scrie oricum.')),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulare', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Formulare',
            },
        ),
        migrations.CreateModel(
            name='TokenTurnator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='', max_length=12, unique=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('folosit', models.BooleanField(default=False)),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokeni', to='core.formular')),
            ],
            options={
                'verbose_name_plural': 'Tokeni Turnători',
            },
        ),
        migrations.CreateModel(
            name='Turnatorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnatorii', to='core.formular')),
            ],
            options={
                'verbose_name_plural': 'Turnătorii',
            },
        ),
    ]
