# Generated by Django 6.0.3 on 2026-03-04 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnatorie',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Persoana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persoane', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Persoane',
            },
        ),
        migrations.CreateModel(
            name='CampFormular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('text', 'Text Liber'), ('optiuni', 'Alegere Multiplă')], max_length=10)),
                ('intrebare', models.CharField(max_length=500)),
                ('optiuni', models.TextField(blank=True, default='')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuri', to='core.formular')),
                ('persoana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuri', to='core.persoana')),
            ],
            options={
                'verbose_name_plural': 'Câmpuri Formular',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='RaspunsCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.TextField(blank=True, default='')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raspunsuri', to='core.campformular')),
                ('turnatorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raspunsuri', to='core.turnatorie')),
            ],
            options={
                'verbose_name_plural': 'Răspunsuri Câmpuri',
            },
        ),
    ]
